name: Docker push
on:
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      -name: get Java
        uses: actions/setup-java@v2
        with:
         distibution: 'adopt'
         java-version: '11'
      - name: Build Jar file
        run: mv clean install

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          contect: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Upload Jar File
        uses: actions/upload-artifact@v2
        with:
          name: my-app.jar
          path: target/*.jar